--SQL to create first 100 records of our motivational databbase
-- Googled top 100 motivational quotes
-- Placed in google sheets
-- did some SPLIT + Concatenate excel functions to format our data into what is seen below
-- created SQL script inserts rows from google docs into 


INSERT INTO Motivational (Src, Msg)
VALUES ('Anonymous',' If you want to achieve greatness stop asking for permission.'),
('John Wooden',' Things work out best for those who make the best of how things work out.'),
('Anonymous',' To live a creative life, we must lose our fear of being wrong.'),
('Jim Rohn',' If you are not willing to risk the usual you will have to settle for the ordinary.'),
('Anonymous',' Trust because you are willing to accept the risk, not because it’s safe or certain.'),
('Swami Vivekananda',' Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.'),
('Walt Disney',' All our dreams can come true if we have the courage to pursue them.'),
('Anonymous',' Good things come to people who wait, but better things come to those who go out and get them.'),
('Anonymous',' If you do what you always did, you will get what you always got.'),
('Winston Churchill',' Success is walking from failure to failure with no loss of enthusiasm.'),
('Proverb',' Just when the caterpillar thought the world was ending, he turned into a butterfly.'),
('Anonymous',' Successful entrepreneurs are givers and not takers of positive energy.'),
('Vaibhav Shah',' Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them.'),
('Chris Grosser',' Opportunities don’t happen, you create them.'),
('Albert Einstein',' Try not to become a person of success, but rather try to become a person of value.'),
('Eleanor Roosevelt',' Great minds discuss ideas; average minds discuss events; small minds discuss people.'),
('Thomas A. Edison',' I have not failed. I’ve just found 10,000 ways that won’t work.'),
('Kim Garst',' If you don’t value your time, neither will others. Stop giving away your time and talents- start charging for it.'),
('David Brinkley',' A successful man is one who can lay a firm foundation with the bricks others have thrown at him.'),
('Eleanor Roosevelt',' No one can make you feel inferior without your consent.'),
('Henry Ford',' The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.'),
('Winston Churchill',' If you’re going through hell keep going.'),
('Anonymous',' The ones who are crazy enough to think they can change the world, are the ones that do.'),
('Anonymous',' Don’t raise your voice, improve your argument.'),
(' Oscar Wilde',' What seems to us as bitter trials are often blessings in disguise.'),
('Anonymous',' The meaning of life is to find your gift. The purpose of life is to give it away.'),
('Bruce Feirstein',' The distance between insanity and genius is measured only by success.'),
('Lolly Daskal',' When you stop chasing the wrong things you give the right things a chance to catch you.'),
('John D. Rockefeller',' Don’t be afraid to give up the good to go for the great.'),
(' Anonymous',' No masterpiece was ever created by a lazy artist.'),
('Nathaniel Hawthorne',' Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you.'),
('Albert Einstein',' If you can’t explain it simply, you don’t understand it well enough.'),
('Anonymous',' Blessed are those who can give without remembering and take without forgetting.'),
('Anonymous',' Do one thing every day that scares you.'),
('Anonymous',' What’s the point of being alive if you don’t at least try to do something remarkable.'),
('Lolly Daskal',' Life is not about finding yourself. Life is about creating yourself.'),
('Anonymous',' Nothing in the world is more common than unsuccessful people with talent.'),
('Anonymous',' Knowledge is being aware of what you can do. Wisdom is knowing when not to do it.'),
('Anonymous',' Your problem isn’t the problem. Your reaction is the problem.'),
('Anonymous',' You can do anything, but not everything.'),
('Steve Jobs',' Innovation distinguishes between a leader and a follower.'),
('Ray Goforth',' There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.'),
('Dr. APJ Kalam',' Thinking should become your capital asset, no matter whatever ups and downs you come across in your life.'),
('Thomas Jefferson',' I find that the harder I work, the more luck I seem to have.'),
('Napolean Hill',' The starting point of all achievement is desire.'),
('Robert Collier',' Success is the sum of small efforts, repeated day-in and day-out.'),
('Thomas J. Watson',' If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work.'),
('Michael John Bobak',' All progress takes place outside the comfort zone.'),
('Philippos',' You may only succeed if you desire succeeding; you may only fail if you do not mind failing.'),
('Mark Twain',' Courage is resistance to fear, mastery of fear - not absense of fear.'),
('Pablo Picasso',' Only put off until tomorrow what you are willing to die having left undone.'),
('Zig Ziglar',' People often say that motivation doesn’t last. Well, neither does bathing - that’s why we recommend it daily.'),
('Earl Nightingale',' We become what we think about most of the time, and that’s the strangest secret.'),
('Vidal Sassoon',' The only place where success comes before work is in the dictionary.'),
('Guy Kawasaki',' The best reason to start an organization is to make meaning; to create a product or service to make the world a better place.'),
('Martha Stewart',' I find that when you have a real interest in life and a curious life, that sleep is not the most important thing.'),
('Anonymous',' It’s not what you look at that matters, it’s what you see.'),
('Colin R. Davis',' The road to success and the road to failure are almost exactly the same.'),
('Ralph Nader',' The function of leadership is to produce more leaders, not more followers.'),
('Maya Angelou',' Success is liking yourself, liking what you do, and liking how you do it.'),
('Bill Gates',' As we look ahead into the next century, leaders will be those who empower others.'),
('Henry Kravis',' A real entrepreneur is somebody who has no safety net underneath them.'),
('Mark Caine',' The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.'),
('Tony Robbins',' People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy'),
('Audre Lorde',' When I dare to be powerful - to use my strength in the service of my vision, then it becomes less and less important whether I am afraid.'),
('Mark Twain',' Whenever you find yourself on the side of the majority, it is time to pause and reflect.'),
('Bruce Lee',' The successful warrior is the average man, with laser-like focus.'),
('Swami Vivekananda',' Take up one idea. Make that one idea your life — think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.'),
('Dale Carnegie',' Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.'),
(' Jim Rohn',' If you don’t design your own life plan, chances are you’ll fall into someone else’s plan. And guess what they have planned for you? Not much.'),
('Gurbaksh Chahal',' If you genuinely want something, don’t wait for it — teach yourself to be impatient.'),
('Robert Kiyosaki',' Don’t let the fear of losing be greater than the excitement of winning.'),
('T. Harv Eker',' If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you! .'),
('Steve Jobs',' You can’t connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future.'),
('Jim Rohn',' Successful people do what unsuccessful people are not willing to doDon’t wish it were easier, wish you were better.'),
('Napoleon Hill',' The number one reason people fail in life is because they listen to their friends, family, and neighbors.'),
('Denis Watiley',' The reason most people never reach their goals is that they don’t define them, or ever seriously consider them as believable or achievable. Winners can tell you where they are going, what they plan to do along the way, and who will be sharing the adventure with them.'),
('Jane Smiley',' In my experience, there is only one motivation, and that is desire. No reasons or principle contain it or stand against it.'),
('George Bernard Shaw',' Success does not consist in never making mistakes but in never making the same one a second time.'),
('Diane Ackerman',' I don’t want to get to the end of my life and find that I lived just the length of it. I want to have lived the width of it as well.'),
('Michael Jordan',' You must expect great things of yourself before you can do them.'),
('Jim Ryun',' Motivation is what gets you started. Habit is what keeps you going.'),
('Dale Carnegie',' People rarely succeed unless they have fun in what they are doing.'),
('Ella Wheeler Wilcox',' There is no chance, no destiny, no fate, that can hinder or control the firm resolve of a determined soul.'),
('Francis Chan',' Our greatest fear should not be of failure but of succeeding at things in life that don’t really matter.'),
('George Lorimer',' You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction.'),
('Mike Gafka',' To be successful you must accept all challenges that come your way. You can’t just accept the ones you like.'),
(' John C. Maxwell',' Success is knowing your purpose in life, growing to reach your maximum potential, and sowing seeds that benefit others.'),
('Wayne Dyer',' Be miserable. Or motivate yourself. Whatever has to be done, it’s always your choice.'),
(' Anatole France',' To accomplish great things, we must not only act, but also dream, not only plan, but also believe.'),
('Dale Carnegie',' Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no help at all.'),
('Booker T. Washington',' You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals.'),
('Theodore N. Vail',' Real difficulties can be overcome; it is only the imaginary ones that are unconquerable.'),
('Herman Melville',' It is better to fail in originality than to succeed in imitation.'),
('Virgil',' Fortune sides with him who dares.'),
('Washington Irving',' Little minds are tamed and subdued by misfortune; but great minds rise above it.'),
('Truman Capote',' Failure is the condiment that gives success its flavor.'),
('John R. Wooden',' Don’t let what you cannot do interfere with what you can do.'),
('Margaret Thatcher',' You may have to fight a battle more than once to win it.'),
('Vince Lombardi',' A man can be as great as he wants to be. If you believe in yourself and have the courage, the determination, the dedication, the competitive drive and if you are willing to sacrifice the little things in life and pay the price for the things that are worthwhile, it can be done.'),